### ISSUE TITLE
Tap outside view boundaries

### ISSUE THREAD

**Issue by Begoodi** [GrandSir/InteractiveMap#4]
I put InteractiveMap in a fixed size view, and added drag and magnification features. OK.
The problem is that the map can be bigger than it's parent when I drap or zoom, and when I tap outside the parent view, InteractiveMap receives the tap even if the tapped part is not displayed.

Taps on InteractiveMap take precedence, even if behind other views.

Any advice ?

**Comment by grandsir** [comment]
I don't think this issue is related with `InteractiveMap` itself.

- Taps on InteractiveMap take precedence, even if behind other views.
This literally can not happen. `InteractiveMap` is just a ZStack of multiple shapes. and it uses GeometryReader to calculate its content size, if you can share your code, I can help to you, but it looks like it is something related with SwiftUI instead of the `InteractiveMap` itself

**Comment by Begoodi** [comment]
Yes you are right, wasn't related to the map. Sorry.
